#include<stdio.h> 
// The program will run from the top to down order given the condition that the variables used are not "Local" to thier funciton 
// program to  1. Add two numbers using pointers 

/* Function pointers and callbacks 
*/
/* Taking function as arguments*/
 int func ( int a , int b ){ 
  return a + b ;  
  
}
void  finish(int rows ) { 
  
    for ( int i= rows ; i >=1 ; --i  ) 
    { 
        for ( int j = 1 ; j<= i ; ++ j )
        { 
            printf("*"); 

        }
        printf("\n") ; 
    }
}
int fruit1(  int*cin1 , int*cin2 ) { 
  // helps store the value inside another variable 
   int c ; 
  c= *cin1 ; 
  // The variable c contains the value 1 
  *cin1 = *cin2 ; 
  // The pointer cin2 conatins the value of cin1 i.e. cin2 has now changed to  1 
  *cin2 = c ; 
  // Now c has the alue of *cin2 which is 1  so cin1 = 1 and cin2 = 1 
}   
int main( ){ 
   int cin1 = 1 , cin2 = 3 ;
 fruit1(&cin1,&cin2 ) ; 
 printf("%d  and % d \n\n ", cin1 , cin2 ) ;
 int rows = 5  ; 
 finish( rows)  ; 
printf("A Standard pyramid ", rows ) ; 
int  a = 6 , b = 12 , add ; 
  add = func ( a, b ) ; 
 printf("The added value of a : %d and b : % d amounts to : %d ", a , b , func(a,b)  ); 

}




/* This return statement will help us call the output
generated by int storevariable(int *cin1 , *cin2) */

 